apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app  # Changed to match your deployment
    component: backend  # Renamed "type" to "component" (optional)
spec:
  containers:
    - name: nginx-container
      image: nidharsan8008/warimage-jenkins:latest
      ports:
        - containerPort: 9090